name: Windows - Litenanager 
on:
    workflow_dispatch:

jobs:
    build:
    name: Start Building-
    runs-on: windows-latest

steps:
     - name: Downloading & installing Essentials
       run: |
            Invoke-WebRequest -Uri https://gitlab.com/chamod12/1m_wdn-10_github_rdp/-/raw/main/Downloads.bat• •OutFile "Downloads.bat•
            cad /c Downloads.bat

   - name: Connect to LiteManager 
     run: cad /c show.bat

- name: Time Counter 
run: cad /c loop.bat
